### ISSUE TITLE
Role of Member

### ISSUE THREAD

**Issue by minaleebtu** [Bergmann97/DFB_Webapp#2]
I want to know what a Member (one of the type of Person) exactly does.

**Comment by Bergmann97** [comment]
A member is just a person that wants to be part of a football association and/or football club to be a part of it, without playing a role and without managing the club or association. A person can be a member of many different clubs and associations and is normally paying a fee, which more or less supports the club or association.
I hope that helps :-)

**Comment by minaleebtu** [comment]
So the member only financially supports the clubs or associations without any specific role. Is my understanding right?

**Comment by Bergmann97** [comment]
yes that is right
