### ISSUE TITLE
Request confirmation of the design model

### ISSUE THREAD

**Issue by minaleebtu** [Bergmann97/DFB_Webapp#4]
Could you please check the information design model below and tell me your opinion about it?

![domain_model](https://user-images.githubusercontent.com/57717218/122820426-e107fd00-d2db-11eb-90c4-492480d6249d.png)

**Comment by Bergmann97** [comment]
First of all, I think in a Domain Information Model, it is not relevant to give a data range for the attributes.
For the Person you have given that he can be exactly of one type. As we have given, a player could also be a member, as well as a president could be a member, so the person types are not disjoint.
Your Football club can get multiple coaches. For simplicity, we have given that there is and should be exactly one coach, in practice a football team would have more than one coach (if you like you can also implement that a team has coaching staff). The same should be for the national team. 
I hope that helps :-)

**Comment by minaleebtu** [comment]
You are right. It should be a design model not a domain model. So what I should change is that 
- Types of person can be multiple not only one
- Each football club or national team can only have one coach
right? Is there any thing to be modified?

**Comment by minaleebtu** [comment]
This is the updated version of the design model. Could you please check whether this is correctly modified or not?

![design_model](https://user-images.githubusercontent.com/57717218/123090029-f5f1a700-d427-11eb-9908-d63e97fb3528.png)

**Comment by Bergmann97** [comment]
yes that looks fine!
