### ISSUE TITLE
Request confirmation of the domain model

### ISSUE THREAD

**Issue by minaleebtu** [Bergmann97/DFB_Webapp#5]
This is the domain information model of your app. I would appreciate if you can have a look and give some feedbacks. Thank you :)

![domain_model](https://user-images.githubusercontent.com/57717218/122971664-921b9f80-d38f-11eb-9d8a-c79442a26c2f.png)

**Comment by Bergmann97** [comment]
This looks quite good. I think there are just a few things that could be changed. As I have seen, a player can be in multiple national teams and football clubs, as well as for the coach. For the president it is fine that he can be president of multiple football associations, but I think there is missing the relation to football clubs. All other looks good

**Comment by minaleebtu** [comment]
Thank you for your feedback. I changed what you mentioned. Is this correct?

![domain_model](https://user-images.githubusercontent.com/57717218/123089932-dc505f80-d427-11eb-961a-c3a9c589b2b1.png)

**Comment by Bergmann97** [comment]
yes looks fine now!
